# Generated by Django 5.1.7 on 2025-03-11 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_remove_transaction_counterparty_tags_and_more'),
        ('ecosystem', '0002_counterpartytag_counterparty_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accuralbudget',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='counterparty_tag',
        ),
        migrations.CreateModel(
            name='CounterPartyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counterparty_tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='ecosystem.counterpartytag')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counter_parties', to='budget.transaction')),
            ],
        ),
    ]
