# Generated by Django 5.1.7 on 2025-03-10 13:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccuralBudgetValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveBigIntegerField(verbose_name='value')),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='number')),
                ('year', models.PositiveIntegerField(verbose_name='number')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget.account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CashBudgetValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveBigIntegerField(verbose_name='value')),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='number')),
                ('year', models.PositiveIntegerField(verbose_name='number')),
                ('budget_value', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget.accuralbudgetvalue')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
