# Generated by Django 5.1.7 on 2025-03-11 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_remove_accuralbudget_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accuralbudget',
            name='counter_party_transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='accural_budgets', to='budget.counterpartytransaction'),
            preserve_default=False,
        ),
    ]
