# Generated by Django 5.1.7 on 2025-03-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_transactiontag_transaction_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='tags',
        ),
        migrations.AddField(
            model_name='counterpartytransaction',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='transactions', to='budget.transactiontag'),
        ),
    ]
