# Generated by Django 5.1.7 on 2025-03-10 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_classification_account_classification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='classification',
        ),
        migrations.DeleteModel(
            name='Classification',
        ),
    ]
