# Generated by Django 5.1.7 on 2025-03-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_remove_transaction_tags_counterpartytransaction_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accuralbudget',
            name='value',
            field=models.BigIntegerField(verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='cashbudget',
            name='value',
            field=models.BigIntegerField(verbose_name='value'),
        ),
    ]
