# Generated by Django 5.1.7 on 2025-03-10 13:39

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_classification_account_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='budget.classification'),
        ),
        migrations.AlterField(
            model_name='account',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='budget.account'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='financial_statement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_statements', to='budget.financialstatement'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='budget.classification'),
        ),
    ]
