# Generated by Django 5.1.7 on 2025-03-15 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_alter_accuralbudget_value_alter_cashbudget_value'),
        ('ecosystem', '0002_counterpartytag_counterparty_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counterpartytransaction',
            name='counterparty_tag',
        ),
        migrations.AddField(
            model_name='counterpartytransaction',
            name='counterparty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='ecosystem.counterparty'),
            preserve_default=False,
        ),
    ]
