# Generated by Django 5.1.7 on 2025-03-10 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_alter_account_classification_alter_account_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='level',
        ),
        migrations.RemoveField(
            model_name='account',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='account',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='account',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='account',
            name='tree_id',
        ),
    ]
