# Generated by Django 5.1.7 on 2025-03-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_remove_counterpartytransaction_counterparty_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accuralbudget',
            name='value',
            field=models.BigIntegerField(default=0, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='cashbudget',
            name='value',
            field=models.BigIntegerField(default=0, verbose_name='value'),
        ),
    ]
