# Generated by Django 5.1.7 on 2025-03-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_alter_accuralbudget_value_alter_cashbudget_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialstatement',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='slug'),
        ),
    ]
