# Generated by Django 5.1.7 on 2025-03-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_financialstatement_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialstatement',
            name='material_ui_icon',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='material_ui_icon'),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='slug',
            field=models.SlugField(default=1, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
