# Generated by Django 5.1.7 on 2025-03-11 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterpartyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
        ),
        migrations.AddField(
            model_name='counterparty',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparties', to='ecosystem.counterpartytag'),
        ),
    ]
