# Generated by Django 5.2 on 2025-04-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosystem', '0002_counterpartytag_counterparty_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='counterpartytag',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
    ]
